### ISSUE TITLE
SCIMessage type for non SCIP Messages

### ISSUE THREAD

**Issue by Mese96** [ctiedt/rasta-rs#1]
Currenty the library assumes scip messages in the `impl TryFrom<u8> for SCIMessageType ` 

See the scils minimal example and needed changes https://github.com/mese96/rasta-rs/commit/18ad2ef7f43cf6403085baa2f31c974c68948d10 

A more general approach is needed, maybe using the try_as_.... functions from SCIMessageType ?

**Comment by ctiedt** [comment]
Good point, thanks for spotting the missing implementation! I think there are two possible solutions here:

1. Remove the `TryFrom<u8>` implementation and write analogous functions to `try_as_...` as you mentioned.
2. Replace `SCIMessageType` with a trait and have separate enums for SCI-P and SCI-LS messages.

I think the first option is lower friction, although I'm not sure how many places depend on the `TryFrom` implementation. Option 2 is probably cleaner, but might be more work to implement. If you have any ideas or other suggestions, I'm happy to discuss them.

**Comment by Mese96** [comment]
After the decision to go with variant 1 for now, I have made some changes at: https://github.com/Mese96/rasta-rs/commit/2294c1fe3f3797c2b6dc536f3c8d9e0e7dcf3d19
That should be enough for now. 
Can you check @ctiedt ?

**Comment by ctiedt** [comment]
Looks good to me, please open a PR and I'll merge these changes.
